name: ATMOS-BUD CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install setuptools and wheel
        run: |
          pip install setuptools wheel

      - name: Run tests with pytest
        run: |
          pytest

      # Build distribution (sempre executa para validar)
      - name: Build distribution
        run: |
          python setup.py sdist bdist_wheel

      # Publish to PyPI (APENAS quando push para main, não em PRs)
      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        