name: Compile JOSS Paper PDF

on:
  push:
    paths:
      - paper/**
      - .github/workflows/compile-joss-paper.yml

jobs:
  build-paper:
    name: Build paper with lualatex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Install Pandoc and citeproc
        run: sudo apt-get install -y pandoc

      - name: Compile paper with Pandoc using lualatex
        run: |
          cd paper
          pandoc paper.md \
            --from markdown \
            --to pdf \
            --pdf-engine=lualatex \
            --citeproc \
            --bibliography=paper.bib \
            -o paper.pdf

      - name: Upload generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf
